/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_1001587_7[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale_1001587_7[3] = { 1.0000000062111045, 1.0000000034229024, 1.0000000131272964 };
const float ei_classifier_anom_mean_1001587_7[3] = { -4.0640360584446024e-9, 3.4304285495012416e-9, 7.0766819750561435e-9 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_1001587_7[32] = {
	{ ( float[3] ) { -1.4331384897232056, 0.794118344783783, -0.8533894419670105 }, 0.4556796323062602 },
	{ ( float[3] ) { -0.8413152694702148, -0.17052902281284332, -0.8495668768882751 }, 0.4474716679829342 },
	{ ( float[3] ) { -0.30661001801490784, -0.4975399971008301, -0.8338177800178528 }, 0.44290753229615315 },
	{ ( float[3] ) { 0.7259809970855713, -0.43283429741859436, -0.7186232805252075 }, 0.5311717409786394 },
	{ ( float[3] ) { -0.8665059208869934, 0.5274612903594971, -0.8557830452919006 }, 0.24061417588724826 },
	{ ( float[3] ) { -0.38742563128471375, -0.5196818113327026, -0.07072897255420685 }, 0.5884053986557396 },
	{ ( float[3] ) { 0.5450775027275085, -0.3945775628089905, 0.9053205847740173 }, 0.5290807056152006 },
	{ ( float[3] ) { 0.2561505138874054, -0.5180748105049133, -0.5861250758171082 }, 0.44595180320347994 },
	{ ( float[3] ) { 0.7522584199905396, -0.44990941882133484, 1.7051531076431274 }, 0.42230100685809213 },
	{ ( float[3] ) { 0.8083486557006836, -0.4959946274757385, 1.196238398551941 }, 0.4564733625134503 },
	{ ( float[3] ) { -1.181230068206787, 2.754760980606079, -0.865034818649292 }, 0.33347468073778813 },
	{ ( float[3] ) { 1.6208593845367432, -0.5055193901062012, 1.3960736989974976 }, 0.26648070773551213 },
	{ ( float[3] ) { -0.7890411019325256, 0.2258453220129013, -0.8459831476211548 }, 0.5014552841948426 },
	{ ( float[3] ) { -0.534389317035675, -0.5133658051490784, -0.6260445713996887 }, 0.47412297478537213 },
	{ ( float[3] ) { -1.1677557229995728, 3.2773818969726562, -0.8571009635925293 }, 0.22035260133011625 },
	{ ( float[3] ) { 2.0425496101379395, -0.4416531026363373, 1.365561842918396 }, 0.4183045587066625 },
	{ ( float[3] ) { -1.1217670440673828, -0.2727148234844208, -0.8652347326278687 }, 0.18510158846134173 },
	{ ( float[3] ) { 1.983330488204956, -0.47221899032592773, 1.7916349172592163 }, 0.31993179224222645 },
	{ ( float[3] ) { -0.9812917113304138, 1.107197642326355, -0.8515757322311401 }, 0.3649394167478057 },
	{ ( float[3] ) { -0.21217253804206848, -0.5275515913963318, -0.44707155227661133 }, 0.2851935798205354 },
	{ ( float[3] ) { 1.9070208072662354, -0.44033071398735046, 0.8802927732467651 }, 0.39467523688407596 },
	{ ( float[3] ) { 1.4091694355010986, -0.44798943400382996, 0.8232095837593079 }, 0.5259648605633049 },
	{ ( float[3] ) { 0.26375022530555725, -0.45795464515686035, 1.4663589000701904 }, 0.4628466843098572 },
	{ ( float[3] ) { -0.021458016708493233, -0.5139172077178955, 0.4521429240703583 }, 0.43497668214973456 },
	{ ( float[3] ) { 1.2964426279067993, -0.4023253321647644, 1.3037152290344238 }, 0.2380934114536202 },
	{ ( float[3] ) { 0.8480001091957092, -0.4193854331970215, 0.4958709180355072 }, 0.3693630669679429 },
	{ ( float[3] ) { 1.4613765478134155, -0.4742166996002197, 1.7968530654907227 }, 0.272721015719222 },
	{ ( float[3] ) { 0.7254602909088135, -0.4458431303501129, -0.0974806472659111 }, 0.5219697937244654 },
	{ ( float[3] ) { -1.2103769779205322, 1.6874449253082275, -0.8562431335449219 }, 0.37745152168188745 },
	{ ( float[3] ) { -1.162166953086853, 2.0805304050445557, -0.8584742546081543 }, 0.262262587609387 },
	{ ( float[3] ) { -1.15359628200531, 3.6560986042022705, -0.8692232370376587 }, 0.2933594342696204 },
	{ ( float[3] ) { -1.252274751663208, 0.07007314264774323, -0.8646542429924011 }, 0.2718843711218535 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
