/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_1001587_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1001587_1[] = { "Idle", "Right", "Up" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1001587_3_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_1001587_3_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1001587_3 = {
    3, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    8.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    64, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1001587_3[33] = { 1832.503907955394, -2.411755461506226, 8.527405745717331, 2.925795947570427, 8.640298370637145, 7.663182317509371, 7.482220785290587, 7.349556645692563, 7.227153415773429, 7.033507970267651, 6.55419872414832, 2284.107672066782, 0.3901445898178317, 0.6038122440975926, 3.8646725001288393, 14.935091377356473, 7.570983353783102, 6.949703897681891, 6.738448379086513, 6.4395893330667535, 6.225989657523585, 5.943691389233458, 5073.444984106924, -2.799186577834189, 10.449185856066498, 3.099649216965133, 10.107171401089312, 8.58313618547776, 8.308031714196298, 8.072036650134068, 7.9256062545028385, 7.731909146028406, 7.29539585908254 };
const float ei_dn_standard_scaler_scale_1001587_3[33] = { 0.0010146062351201936, 0.7129843199030734, 0.14287256994982542, 1.1131015818836538, 0.15304036858973913, 1.6955191308877773, 2.1465623110122207, 2.574711150324626, 2.6077023170529636, 2.6276707012410427, 2.5238784243815826, 0.0005330142502828452, 1.0221681673162901, 0.2734357748551821, 1.2029820544504568, 0.15797911647393256, 0.7285253147815489, 1.0106739374494174, 1.187436267996014, 1.1739967595974252, 1.1430156340916549, 1.124750147585628, 0.00031150394786222277, 0.5811743993532983, 0.11382664279903652, 0.8613346317017161, 0.11894002364326395, 1.5675518379831257, 3.0300189506886226, 5.951595445251371, 5.453347989440401, 5.429992022799887, 6.064823644264718 };
const float ei_dn_standard_scaler_var_1001587_3[33] = { 971415.31522534, 1.967161618612738, 48.9894187284523, 0.8071056733816013, 42.69607906312701, 0.3478520853359057, 0.21702661682843963, 0.15084918646696457, 0.14705641495373548, 0.1448298639338087, 0.15698680035104337, 3519835.4394703982, 0.9570955482871679, 13.374862643738487, 0.691005815559588, 40.068274349084334, 1.884129309718385, 0.9789891235533295, 0.7092173982519295, 0.7255480907306041, 0.7654126906755615, 0.7904745324145054, 10305590.698472513, 2.9606498623710653, 77.18131008565116, 1.3478953699019376, 70.68771757397481, 0.4069641719897623, 0.10892042080972325, 0.028231450646290276, 0.033625873620926366, 0.0339157649577149, 0.027187147690802858 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1001587_3 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1001587_3,
    .mean_data_len = 33,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1001587_3,
    .scale_data_len = 33,
    .var_data = (float *)ei_dn_standard_scaler_var_1001587_3,
    .var_data_len = 33
};
ei_data_normalization_t ei_data_normalization_config_1001587_3 = {
    (void *) &ei_data_normalization_standard_scaler_config_1001587_3, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1001587_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1001587_1[ei_dsp_blocks_1001587_1_size] = {
    { // DSP block 3
        3,
        33, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1001587_3, // pointer to config struct
        ei_dsp_config_1001587_3_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1001587_3_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1001587_3, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1001587_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1001587_5_init,
    .model_invoke = &tflite_learn_1001587_5_invoke,
    .model_reset = &tflite_learn_1001587_5_reset,
    .model_input = &tflite_learn_1001587_5_input,
    .model_output = &tflite_learn_1001587_5_output,
};

const uint8_t ei_output_tensors_indices_1001587_5[1] = { 0 };
const uint8_t ei_output_tensors_size_1001587_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1001587_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_1001587_5,
    .output_tensors_size = ei_output_tensors_size_1001587_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1001587_5,
    .dequantize_output = 0,
};

const ei_learning_block_config_anomaly_kmeans_t ei_learning_block_config_1001587_7 = {
    .implementation_version = 1,
    .block_id = 7,
    .anom_axis = ei_classifier_anom_axes_1001587_7,
    .anom_axes_size = 3,
    .anom_clusters = ei_classifier_anom_clusters_1001587_7,
    .anom_cluster_count = 32,
    .anom_scale = ei_classifier_anom_scale_1001587_7,
    .anom_mean = ei_classifier_anom_mean_1001587_7,
};

const uint8_t ei_learning_blocks_1001587_1_size = 2;
const uint32_t ei_learning_block_1001587_5_inputs[1] = { 3 };
const uint8_t ei_learning_block_1001587_5_inputs_size = 1;
const uint32_t ei_learning_block_1001587_7_inputs[1] = { 3 };
const uint8_t ei_learning_block_1001587_7_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1001587_1[ei_learning_blocks_1001587_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1001587_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1001587_5_inputs,
        ei_learning_block_1001587_5_inputs_size,
    },
    {
        7,
        &run_kmeans_anomaly,
        (void*)&ei_learning_block_config_1001587_7,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1001587_7_inputs,
        ei_learning_block_1001587_7_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1001587_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1001587_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1001587_1[ei_postprocessing_blocks_1001587_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1001587_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_1001587_1_size = 0;

uint32_t *freeform_outputs_1001587_1 = nullptr;

const ei_impulse_t impulse_1001587_1 = {
    .project_id = 1001587,
    .project_owner = "Maria_Eduarda_Santos",
    .project_name = "Maria_Eduarda_Santos-project-1",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 2,

    .nn_input_frame_size = 33,
    .raw_sample_count = 168,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 168 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 11.904761904761905,
    .frequency = 84,

    .dsp_blocks_size = ei_dsp_blocks_1001587_1_size,
    .dsp_blocks = ei_dsp_blocks_1001587_1,

    .learning_blocks_size = ei_learning_blocks_1001587_1_size,
    .learning_blocks = ei_learning_blocks_1001587_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1001587_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1001587_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "x + y + z",
    .slice_size = (168/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_KMEANS,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_1001587_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1001587_1_size,
    .freeform_outputs = freeform_outputs_1001587_1
};

ei_impulse_handle_t impulse_handle_1001587_1 = ei_impulse_handle_t( &impulse_1001587_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1001587_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1001587_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1001587_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1001587_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
